-- Fix foreign key references on transactions so Supabase/PostgREST can join
-- transactions → profiles automatically.
--
-- The original schema has buyer_id and seller_id referencing auth.users(id).
-- PostgREST cannot follow  transactions.seller_id → auth.users ← profiles
-- so any query like  .select('*, profiles:seller_id(*)')  silently errors,
-- returning zero rows and showing "No purchases yet" / empty My Sales.
--
-- This migration re-points those FKs to public.profiles(id) instead.
-- profiles.id is a 1-to-1 with auth.users.id (same UUID), so data is unchanged.
--
-- Run ONCE in Supabase SQL Editor.

-- Drop old FK constraints (names generated by Postgres from table+column)
ALTER TABLE public.transactions
  DROP CONSTRAINT IF EXISTS transactions_buyer_id_fkey,
  DROP CONSTRAINT IF EXISTS transactions_seller_id_fkey;

-- Re-add FKs pointing to profiles
ALTER TABLE public.transactions
  ADD CONSTRAINT transactions_buyer_id_fkey
    FOREIGN KEY (buyer_id) REFERENCES public.profiles(id) ON DELETE CASCADE,
  ADD CONSTRAINT transactions_seller_id_fkey
    FOREIGN KEY (seller_id) REFERENCES public.profiles(id) ON DELETE CASCADE;
